<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.minirpc</groupId>
    <artifactId>mini-rpc</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>mini-rpc</name>

    <modules>
        <module>rpc-core</module><!--放公共协议、编解码、请求响应模型，这些是客户端和服务端都要用的-->
        <module>rpc-client</module><!--放客户端发送请求、连接管理、响应回填这些逻辑，比如 RpcClient-->
        <module>rpc-server</module><!--放服务端监听端口、收请求、反射执行，比如 RpcServer-->
        <module>rpc-registry</module><!--放服务注册与发现，比如 RegistryCenter 和 ZookeeperRegistryCenter-->
        <module>rpc-demo</module><!--放演示启动类和示例服务，比如 ClientBootstrap 和 ServerBootstrap-->
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <netty.version>4.1.65.Final</netty.version>
        <curator.version>5.7.1</curator.version>
    </properties>
</project>
